r"""Compare assembler output with reference files generated by real zasm.

Reference files are generated by c:\zasm\zasm.exe with --date=2026-09-19,11:06:55.
Naming convention: #target bin -> *.bin, #target ram/rom -> *.rom
"""
import sys
import os
import datetime
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from assemble8080.assembler import assemble

TEST_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'ASM_FOR_TEST')

# Fixed datetime for reproducible __date__/__time__ (must match zasm --date)
FIXED_NOW = datetime.datetime(2026, 9, 19, 11, 6, 55)

# Reference files (generated by real zasm compiler)
REFS = [
    '8080TonePlayer.bin',
    'bf.bin',
    'CPU_test.rom',
    'ESC_DeESC.bin',
    'fifo_a16.bin',
    'ImperialMarch.bin',
    'IMSAI8080.bin',
    'kernel.rom',
    'main_boot.rom',
    'Mega-80.rom',
    'mon85-v13.rom',
    'rtty.bin',
    'shell.rom',
    'Smyk_player.rom',
    'SW_IO.rom',
]

print(f"Каталог тестов: {TEST_DIR}")
print(f"Файлов для проверки: {len(REFS)}")
print(f"Фиксированная дата: {FIXED_NOW}")
print("=" * 70)

passed = 0
failed = 0

for ref_name in REFS:
    ref_path = os.path.join(TEST_DIR, ref_name)
    if not os.path.exists(ref_path):
        print(f"  SKIP {ref_name}: файл не найден")
        continue

    # Determine source file name (strip .bin or .rom)
    base = os.path.splitext(ref_name)[0]
    # Try common extensions
    src_name = None
    for ext in ['.asm', '.mac', '.s']:
        candidate = base + ext
        if os.path.exists(os.path.join(TEST_DIR, candidate)):
            src_name = candidate
            break

    if src_name is None:
        print(f"  SKIP {ref_name}: не найден исходный файл (искали {base}.*")
        continue

    src_path = os.path.join(TEST_DIR, src_name)

    # Read reference binary
    with open(ref_path, 'rb') as f:
        ref_data = f.read()

    # Assemble with fixed datetime
    with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
        source = f.read()

    res = assemble(source, filename=src_path, now=FIXED_NOW)

    if res.errors:
        print(f"  FAIL {src_name}: ошибки сборки ({len(res.errors)})")
        for e in res.errors[:3]:
            print(f"     Line {e.line}: {e.message}")
        failed += 1
        continue

    asm_data = bytes(res.binary)

    # Compare
    if asm_data == ref_data:
        print(f"  OK   {src_name}: {len(asm_data)} байт — совпадает")
        passed += 1
    else:
        # Find first difference
        min_len = min(len(asm_data), len(ref_data))
        diff_pos = -1
        for i in range(min_len):
            if asm_data[i] != ref_data[i]:
                diff_pos = i
                break

        if diff_pos == -1:
            # One is prefix of the other
            if len(asm_data) > len(ref_data):
                diff_pos = len(ref_data)
                print(f"  FAIL {src_name}: ассемблер длиннее ({len(asm_data)} vs {len(ref_data)})")
            else:
                diff_pos = len(asm_data)
                print(f"  FAIL {src_name}: ассемблер короче ({len(asm_data)} vs {len(ref_data)})")
        else:
            print(f"  FAIL {src_name}: различие с байта {diff_pos} (0x{diff_pos:04X})")
            print(f"     Ассемблер: {asm_data[diff_pos]:02X}")
            print(f"     Референс:  {ref_data[diff_pos]:02X}")
            # Show context
            ctx_start = max(0, diff_pos - 4)
            ctx_end = min(min_len, diff_pos + 8)
            print(f"     Контекст ассемблера: {asm_data[ctx_start:ctx_end].hex(' ')}")
            print(f"     Контекст референса:  {ref_data[ctx_start:ctx_end].hex(' ')}")

        # Count total differences
        total_diffs = sum(1 for i in range(min_len) if asm_data[i] != ref_data[i])
        if len(asm_data) != len(ref_data):
            total_diffs += abs(len(asm_data) - len(ref_data))
        print(f"     Размеры: ассемблер={len(asm_data)}, референс={len(ref_data)}, различий={total_diffs}")
        failed += 1

print("=" * 70)
print(f"Итог: {passed} совпало, {failed} различий")
