[profiles.empty]
description = "Пустая система (без устройств)"

[profiles.empty.system]
name = "Empty System 64k RAM"
cpu = "i8080"
clock_mhz = 2

[[profiles.empty.memory.regions]]
type = "ram"
start = 0x0000
end = 0xFFFF
