;********************************
;     " O R I O N S O F T "
;
;    ===== ν ο ξ ι τ ο ς =====
;
;   δμρ βαϊοχοηο πλ "ORION-128"
;
;      VERSION: M4.00 BETA
;
;      οτ  23 ολτρβςρ 1994
;
;    πςογεσσος	- I8080  (Z80)
;    λμαχιατυςα - MC7007 (RK86)
;*********************************
;
ON	ASET	1
OFF	ASET	0
;
;
;-------------------------------------
;   λμαχιατυςα  νσ/ςλ
;
MS	ASET	OFF
;
;-------------------------------------
;    π/π BEEP
;
Z80CPU	ASET	ON
;
;-------------------------------------
;
STACK	EQU	0F3C0H ; ξαώ.αδς.στελα
;
;
;ποςτ KBRD
PKA	EQU	0F400H
PKB	EQU	0F401H
PKC	EQU	0F402H
PKU	EQU	0F403H
;
;ποςτ ROM-δισλ
PDA	EQU	0F500H
PDB	EQU	0F501H
PDC	EQU	0F502H
PDU	EQU	0F503H
;
;
	.PHASE	0F800H 
;
;
;
START:	JP	ST1	  ;F800
KBX:	JP	KB	  ;F803 χθ.ξα ππ οβς.λμ-ςω
	JP	RESET0    ;F806 χοσταξ.ςαβ.ρώ.νοξιτοςα
TVX:	JP	TVST	  ;F809 -"-χωχ.σινχ.ξα TV
MASC:	JP	MASC_	  ;F80C (F3C9) υπς.CURSOR
	JP	TV	  ;F80F -"-χωχ.σινχ (A)=>TV
	JP	STTS      ;F812 -"-πςOχ.στατ.λμαχ.
	JP	HEX       ;F815 -"-βακτ=>TV(2ASCII)
	JP	MSG       ;F818 -"-χωχ.σινχ.σοοβύ.
	JP	INKEY     ;F81B χχοδ λοδα ξαφ.λμαχ.
	JP	RCUR      ;F81E πομοφεξιε λυςσοςα
	JP	PUSTO     ;F821 ςεϊεςχ δμρ "PRO"/F.ROM1
	JP	CLS       ;F824
	JP	TRANS     ;F827
	JP	CSM       ;F82A σώετ λοξτς.συννω
	JP	RPAC      ;F82D ςασπαλοχλα ϊξαλ.ηεξ
	JP	PUSTO     ;F830 ςεϊεςχ δμρ "PRO"
	JP	PUSTO     ;F833 ςεϊεςχ δμρ "PRO"
	JP	RRAM      ;F836 ώτ.βακτα δοπ.στςαξ.
	JP	WRAM      ;F839 ϊπ.βακτα δοπ.στςαξ.
	JP	WCUR      ;F83C υσταξοχλα λυςσοςα
BPX:	JP	VIRUS     ;F83F χθ.χ ϊχυλ.σιξτεϊ
;
;
	DB	'V4.0'     ; χεςσιρ "V4.0"
;
; σοοβύεξιε πςι οτσυτστχ.
; ROM-δισλα
;
TABER:	DB	1FH,0AH
	DB	'M4.0/I_RK DISK?',0
;
;
ST1:	IF	Z80CPU
	LD	HL,(0F3C1H)
	LD	SP,0F3BFH
	POP	BC
	PUSH	HL
	SCF
	ADC	HL,BC	;Z80
	RET	Z
	ENDIF
;
	LD	SP,STACK
	XOR	A
	OUT	(0F8H),A     ;χωλμ.σταςτ.νεθ.
	OUT	(0F9H),A
	OUT	(0FAH),A
	OR	80H
	OUT	(0FBH),A     ;χωλμ.δισπετώες
;
        CALL	RESET   ;ιξιγιαμ.σμυφ.ρώεκλι
	CALL	RPAC    ;ςασπαλ.ϊη
;
UR:	LD	SP,STACK ;"τεπμωκ σταςτ"
;
	IF	MS
	LD	A,98H
	ELSE
	LD	A,8AH
	ENDIF

	LD	(PKU),A

ST60:	LD	A,90H
	LD	(PDU),A      ;πςοη.ποςτ ROM-DISK
	LD	HL,0
ST6:	CALL	STI
	LD	B,A
	CALL	STI
	CP	B	     ;ROM - ποδλμΰώεξ?
	JP	Z,ST2
;
	DEC	HL
	DEC	HL
	LD	A,0C3H
	CP	B
	JP	NZ,ST70
	LD	BC,0800H  ;ηςυϊιτψ βμολ ORDOS
	LD	DE,0B800H ;χ σταςον χαςιαξτε
	CALL	ST8
	JP	0BFFDH
;
; εσμι πεςχωκ βακτ ROM-δισλα ξε "C3",
; το ϊαηςυϊ. χ ξοχον ζοςνατε.
;
; 0001 0203 0405.....0F - αδς.ROM-δισλα
;  \/	\/   \/
;   I	 I    - αδς.ποσαδ.ζμ.χ οϊυ+START
;   I	  - ςαϊνες ϊαηςυφ.βμολα
;    - αδς.ςαϊνεύ.ζμ. χ ROM
;
;ξοχωκ ϊαηςυϊώιλ!!!
;
ST70:;LD	HL,(0B802H)  ;SIZE
;LD	B,H
;LD	C,L
;LD	HL,(0B804H)  ;RAM
;PUSH	HL
;EX	DE,HL
;LD	HL,(0B800H)  ;ROM
;
	CALL	STI
	LD	E,A
	CALL	STI
	LD	D,A
	CALL	STI
	LD	C,A
	CALL	STI
	LD	B,A
	PUSH	DE
	CALL	STI
	LD	E,A
	CALL	STI	
	LD	D,A
	POP	HL
	PUSH	DE
;
ST8:	CALL	STI
	LD	(DE),A
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JP	NZ,ST8
	RET
;
STI:	LD	(PDB),HL
	LD	A,(PDA)
	INC	HL
	RET        	;47
;
ST2:	LD	HL,TABER
	CALL	MSG
	CALL	KBRD
	JP	ST60
;
; ππ.ςασπαλοχλι ZG
;
RPAC:	LD	DE,NAZG     ; 0FE4AH
	LD	HL,(ZNAK1)
ZF903:	LD	(HL),0
        INC	HL
      	LD	C,7
ZF908:	INC	DE
	LD	A,D
	OR	E
	RET	Z
	LD	A,(DE)
	RLCA
	RLCA
	RLCA
	AND	7
	INC	A
	LD	B,A
	LD	A,(DE)
	AND	1FH
ZF917:	LD	(HL),A
	INC	HL
	DEC	C
	JP	Z,ZF903
	DEC	B
	JP      NZ,ZF917
	JP	ZF908
;
KUS:
;
; βμολ ισθοδξοηο σοστορξιρ ρώ.
; MON-4. πεςεξοσιτσρ πςι "θ-σταςτε"
; χ οβμαστψ οϊυ - F3C3-F3F2H
;-----------------------
; F3C3!
;
	.DEPHASE
	.PHASE	0F3C3H
;
VIRUS:	JP	BEEP	  ;F3C3-..C5
KB:	JP	KBRD      ;F3C6-..C8
MASC_:  JP	CURSOR    ;F3C9-..CB
TVST:   JP	TV2       ;F3CC-..CE
;
EKRAN:  DB	0C0H      ;F3CF EKRAN
EKRED:  DB	30H       ;F3D0 EKRED
ZNAK1:  DW	0F000H    ;F3D1 ZG 20-7F
INVERS: DB	0         ;F3D3 INVER
SWIN:   DB	0         ;F3D4 SWIN;χωσοτα ολξα
;
PAGE:   DB	0         ;F3D5 PAGE;ξε ϊαξινατψ
;
TVAD:   DW	0         ;F3D6 TVAD
TVAD1	EQU	TVAD+1
;
ZNAK2:  DW	0F000H    ;F3D8 ZG 80-FF
;
TSU:    DB	0         ;F3DA INKEY
TSH:    DB	0         ;F3DB INKEY
TBT:    DB	0         ;F3DC ϊαξρτο MOVE,INKEY
TB1:    DB	0         ;F3DD ϊαξρτο MOVE,TVC - ςαβ. ρώεκλα
;
AR2:    DB	0         ;F3DE ESC
;
        DW	UR        ;F3DF οβς. πςες. ξε ϊαξινατψ!
;
VSTACK: DW	0         ;F3E1 σοθς. υλ. στελα
IKEYTM: DB	0   ;00H! ;F3E3 IKEYTM
;
        DB	0         ;F3E4 XCUR - ξε ισπ.
;
FFIX:   DB	0         ;F3E5 FL= RUS/LAT
SIMV:   DB	0         ;F3E6 ποσμ. χχεδ. σινχ. KBRD
CBEEP:  DB	3FH       ;F3E7 λοξστ.BEEP
TBRUS:  DW	0F800H    ;F3E8 ταβ. χεςθ. ςεη INKEY
TBLAT:  DB	0         ;F3EA σνεύ. δμρ ξιφ. ςεη
FLTABIN:DB	0         ;F3EB ζμαη ισπ. ταβμ INKEY
;
;  ζοςνιςοχαξιε ζμαηα:
; TBRUS: DW     XXXXH   ;ξαώαμο ςυσ. ταβμ.
;               +       
; TBLAT: DB	00YYH   ;σνεύεξιε
;                          
;               = ZZZZH : ξαώαμο ματ. ταβμ.
;
; FLTABIN = (LOW ZZZZH) XOR 5AH  ;ζμαη ισπ. ταβμ. INKEY
;
;
STTSV:  DW	STTS_     ;F3EC STTS
TVAV:   DW	TV_A      ;F3EE TV_A
IKEYV:  DW	I_KEY     ;F3F0 INKEY
TMKBD:  DB	2FH       ;F3F2 KBRD WAIT
;
ENDVIR:
;
	.DEPHASE
	.PHASE	KUS+ENDVIR-VIRUS
;
;---------------------------
; ππ.πεςεξοσα βμολα ισθοδ.
; σοστ.ρώ.χ οϊυ
;
RESET0:	OR	A
	RET	NZ
RESET:	LD	HL,KUS
	LD	DE,VIRUS
	LD	B,ENDVIR-VIRUS
RS:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	JP	NZ,RS
	RET
;
;ππ.χωχοδα ξα TV
;βακτ=2ASCII
;
HEX:	PUSH	AF
	RRCA
	RRCA
	RRCA
	RRCA
	CALL	AS1
	POP	AF
AS1:	AND	0FH
	CP	0AH
	JP	M,AS2
	ADD	A,07H
AS2:	ADD	A,30H
TV20:	PUSH	BC
	LD	C,A
	CALL	TVX
	POP	BC
PUSTO:	RET            ;βμ.πυστωθ χελτοςοχ
;
;
; ππ.χωχοδ στςολι σοοβύεξιρ
;
MSG:	LD	A,(HL)
	AND	A
	RET	Z
	CALL	TV20
	INC	HL
	JP	MSG
;
;ππ ποδσώετα λοξτςομψξοκ συννω
;
;
CSM:	EX	DE,HL
	PUSH	HL
	LD	A,L
	LD	HL,0
	JP	CSM2
CSM1:	EX	DE,HL
	LD	B,(HL)
	LD	C,B
	INC	HL
	EX	DE,HL
	ADD	HL,BC
CSM2:	CP	E
	JP	NZ,CSM1
	POP	BC
	PUSH	BC
	LD	A,B
	CP	D
	LD	A,C
	JP	NZ,CSM1
	LD	A,(DE)
	ADD	A,L
	LD	C,A
	LD	B,H
	POP	HL
	RET
;
;
WCUR:	LD	A,L	  ;υστ.λυςσος
	RLCA
	RLCA
	LD	L,A
	LD	(TVAD),HL
RCUR:	LD	HL,(TVAD)	  ;ώιτ.πομοφεξιε
	LD	A,L
	RRCA
	RRCA
	LD	L,A
	RET
;
; ππ ώτεξιρ/ϊαπισι
; βακτα χ δς.στςαξιγυ
;
;
WRAM:	OUT	(0F9H),A	  ;ποςτ στςαξιγ
	LD	(HL),C
	XOR	A
	OUT	(0F9H),A
	RET
;
RRAM:	OUT	(0F9H),A
	LD	C,(HL)
	XOR	A
	OUT	(0F9H),A
	RET
;
;
; ππ ϊαπισι λοξστ.χ X-PAGE
;HL=ξ/αδς.
;DE=ςαϊνες
; C=ϊαπισωχαενωκ βακτ
; A - λυδα (PAGE) ϊαπ.βακτ
;
CLS:	AND	03
	OUT	(0F9H),A
	ADD	HL,DE	     ;HL - λ.αδς.
	EX	DE,HL
	XOR	A
	LD	A,H
	RRA
	LD	H,A
	LD	A,L
	RRA
	LD	L,A
	LD	A,C
	LD	B,H
	LD	C,L
	LD	HL,0
	ADD	HL,SP
	EX	DE,HL
	LD	SP,HL
	EX	DE,HL
	LD	D,B
	LD	E,C
	LD	C,A
	LD	B,A
CYC1:	PUSH	BC
	DEC	DE
	LD	A,D
	OR	E
	JP	NZ,CYC1
	LD	SP,HL
	LD	A,(PAGE)
	OUT	(0F9H),A
	RET
;
; ππ πεςεξοσα βμολα PAGE/PAGE
;HL=ξ/αδς.
;DE=ξ/αδς-λυδα
;BC=λομιώ.
; A=0000     - οτλυδα ώιτατψ
;	0000 - λυδα ϊαπισατψ
;  0F3D5     - PAGE_χοϊχςατ
;
TRANS:	PUSH	HL
	LD	HL,2
	ADD	HL,SP
	LD	(VSTACK),HL
	POP	HL
	LD	SP,HL        ;SP=NA_οτλυδα
	EX	DE,HL        ;HL=NA_λυδα
	AND	33H
	LD	(TBT),A      ;λυδα
	RRCA
	RRCA
	RRCA
	RRCA
	LD	(TB1),A      ;οτλυδα
;
TR0:	OUT	(0F9H),A
	POP	DE
	LD	A,(TBT)
	OUT	(0F9H),A
	LD	(HL),E
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JP	Z,TR1
	LD	(HL),D
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	LD	A,(TB1)
	JP	NZ,TR0
TR1:	LD	A,(PAGE)
	OUT	(0F9H),A
	LD	HL,(VSTACK)
	LD	SP,HL       ;χοστ.στελ
	RET
;
; ππ οβςαβοτλι λμαχ-ςω
; (οβύαρ δμρ RK86 ι νσ7007)
; χωχοδ σινχ.πο ξαφατιΰ
;
;---------------------------------------
;---------------------------------------
;π/π 0F803H ιϊ MON-3
;  
;---------------------------------------
;---------------------------------------
;
KBRD:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,STR2
	PUSH	HL
ZFCEE:	LD	DE,0FFH
ZFCF1:	CALL	ZFD3D
	LD	B,A
	LD	HL,VSTACK
	INC	A
	JP	NZ,ZFCFF
ZFCFB:	LD	(HL),1
	JP	ZFCF1
;
ZFCFF:	LD	C,(HL)
ZFD00:	XOR	A
ZFD01:	DEC	A
	JP	NZ,ZFD01
	CALL	ZFD3D
	CP	B
	JP	NZ,ZFCFB
	DEC	C
	JP	NZ,ZFD00
	DEC	(HL)
	LD	A,(TMKBD)
	LD	(HL),A
	JP	Z,ZFD16
	LD	(HL),2
ZFD16:	LD	A,D
	RRCA
	CALL	C,MASC
	CALL	BPX
	LD	A,B
	LD	(SIMV),A
	CP	0FEH
	RET	NZ
	LD	HL,CBEEP
	LD	A,(HL)
	XOR	1FH
	LD	(HL),A
	LD	HL,FFIX
	LD	A,(HL)
	CPL
	LD	(HL),A
RLT:    CALL	INKEY
	CP	0FEH
	JP	Z,RLT
	CALL	BPX
	JP	ZFCEE
;
ZFD3D:	INC	DE
	INC	E
	DEC	E
	CALL	Z,MASC
	JP	INKEY
;
; ππ χλμ/χωλμ λυςσοςα
;
CURSOR:	PUSH	BC
	PUSH	HL
	CALL	MASC1
	ADD	A,9
	LD	L,A
	LD	A,B
	XOR	(HL)
	LD	(HL),A
	INC	H
	LD	A,C
	XOR	(HL)
	LD	(HL),A
	POP	HL
	POP	BC
	RET
;
MASC1:	LD	HL,(TVAD)
	LD	A,L
	RRCA
	LD	L,A
	RRCA
	ADD	A,L
	LD	B,A
	LD	L,H
	LD	A,(EKRAN)
	LD	H,A
	LD	A,B
	DEC	H
M18:	INC	H
	SUB	04H
	JP	NC,M18
	LD	(TB1),A
	PUSH	HL
	LD	HL,0FCH
M19:	ADD	HL,HL
	ADD	HL,HL
	INC	A
	JP	NZ,M19
	LD	B,H
	LD	C,L
	POP	HL
MULT10:	LD	A,L
	RLCA
	RLCA
	RLCA
	ADD	A,L
	ADD	A,L
	LD	L,A
	RET
;
;
;
IF	MS
;
;
;
;&=========================
; σνεξξωε δςακχεςω λμαχ-ςω
;---δμρ ςλ86 ποσμε END!!---
;==========================
;
; ππ.στατυσ KBRD
STTS:	PUSH	HL
	LD	HL,(STTSV)
	EX	(SP),HL
	RET
;
STTS_:	XOR	A
	LD	(PKC),A
	LD	(PKB),A
	LD	A,(PKA)
	INC	A
	RET	Z
;
	LD	A,0FFH
	LD	(PKC),A
	LD	A,0FCH   ; 1-2?
	LD	(PKB),A
	LD	A,(PKA)
	AND	0EBH
	CP	0EBH
	JP	NZ,STS1
;
	LD	A,3      ; 3-8?
	LD	(PKB),A
	LD	A,(PKA)
	INC	A
	JP	NZ,STS1
;
	LD	(PKC),A      ; 9-11?
	LD	A,(PKA)
	INC	A
	JP	NZ,STS1
	RET
;
STS1:	LD	A,0FFH
	RET
;
; ππ.οπςοσα νατςιγω
; λμαχιατυςω
;
INKEY:	PUSH	HL
	LD	HL,(IKEYV)
	EX	(SP),HL
	RET
;
I_KEY:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,STR2
	PUSH	HL

;LD	HL,(TBRUS)
;EX	DE,HL
;LD	HL,TBLAT
;LD	C,(HL)
;EX	DE,HL
;LD	B,0
;ADD	HL,BC
;EX	DE,HL
;INC	HL
;LD	A,(HL)	
;XOR	5AH
;CP	E
;JP	Z,INTABL
;
;
;ORDINARY INKEY FOR MS7007
;
;
INTABL: LD	HL,0FFFFH
	LD	(TSU),HL
	LD	(TSH),HL
	DEC	HL
	LD	C,0
KEY:	LD	(PKB),HL
	LD	A,(PKA)
	CP	0FFH
	JP	Z,KEY4
	LD	B,A
;
	PUSH	HL
	LD	H,5
	LD	A,(IKEYTM)
KYT:	DEC	A
	JP	NZ,KYT
	DEC	H
	JP	NZ,KYT
	POP	HL
;
	LD	A,(PKA)
	CP	B
	JP	NZ,KEY4
;
KEY2:	LD	B,C
	JP	KEY5
KEY3:	INC	C
KEY5:	RRA
	JP	C,KEY3
	LD	A,C
	LD	C,B
	LD	DE,TSU
	CP	0AH  ; συ
	JP	Z,SKL
	CP	4	 ; SHIFT
	INC	DE
	JP	Z,SKL
	CP	14H  ; ζιλσ
	JP	Z,FX
	INC	DE
	DEFB	6	 ; MVI B,0AFH - πυστ. λον.
;
SKL:	XOR	A
	LD	(DE),A
;
KEY4:	LD	A,C
	ADD	A,8
	LD	C,A
	SCF
	LD	A,L
	RLA
	LD	L,A
KEY1:	LD	A,H
	RLA
	LD	H,A
	CP	0F7H
	JP	NZ,KEY
	LD	A,(TBT)
	CP	0FFH
	RET	Z
;
	LD	HL,(TBRUS)
	EX	DE,HL
	LD	HL,(TBRUS)
	LD	A,(TBLAT)
	LD	C,A
	LD	B,0
	ADD	HL,BC

	LD	A,(FFIX)
	AND	A
	JP	Z,KEY6
	EX	DE,HL
KEY6:	LD	A,(TSH)
	AND	A
	JP	NZ,KEY61
	EX	DE,HL
KEY61:	LD	B,0
	LD	A,(TBT)
	LD	C,A
	ADD	HL,BC
	LD	A,(TSU)
	AND	A
	LD	A,(HL)
	RET	NZ
	AND	1FH
	RET
;
FX:	LD  	A,0FEH
	RET
;
;
;
ELSE
;
;
;&------------------------
; PR_KB, STTS, INKEY δμρ
; MON V4.0/RK
;-------------------------
;
; ππ.στατυσ λμαχιατυςω
STTS:	PUSH	HL
	LD	HL,(STTSV)  ;ρώ.πεςεξαϊξαώεξιρ
	EX	(SP),HL
	RET
;
STTS_:;CALL	INTRRP
STAT:   XOR	A	   ;STTS - RK86
	LD	(PKA),A
	LD	A,(PKB)
	INC	A
	RET	Z
	OR	0FFH
	RET
;
; ππ οπςοσα νατςιγω
; λμαχιατυςω (RK86)
INKEY:	PUSH	HL
	LD	HL,(IKEYV)  ;ρώ.πεςεξαϊξαώεξιρ
	EX	(SP),HL
	RET
;
;INTRRP: LD	A,(PKC)
;AND	60H
;RET	NZ
;CALL	ZFD4C
;INC	A
;JP	Z,INTRRP
;INC	A
;RET	NZ
;ZFAFC:	CALL	ZFD4C
;CP	0DH
;JP	NZ,ZFAFC
;ZFB03:  CALL	STAT 
;JP	NZ,ZFB03
;RET
;
;
;
I_KEY:;CALL	INTRRP
;
ZFD4C:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,STR2
	PUSH	HL

;LD	HL,(TBRUS)
;EX	DE,HL
;LD	HL,TBLAT
;LD	C,(HL)
;EX	DE,HL
;LD	B,0
;ADD	HL,BC
;EX	DE,HL
;INC	HL
;LD	A,(HL)
;XOR	5AH
;CP	E
;JP	Z,INTABL
;
;ORDINARY INKEY
;
;LD	HL,PKB
;LD	BC,0FE00H
;ZFD58:	DEC	HL
;LD	(HL),B
;INC	HL
;LD	E,(HL)
;LD	A,0FFH
;CP	E
;JP	Z,ZFD6D
;LD	D,5
;LD	A,(IKEYTM)
;ZFD63:	DEC	A
;JP	NZ,ZFD63
;DEC	D
;JP	NZ,ZFD63
;LD	A,(HL)
;CP	E
;JP	Z,ZFD7D
;ZFD6D:	LD	A,8
;ADD	A,C
;LD	C,A
;RLC	B
;JP	C,ZFD58
;INC	HL
;LD	A,(HL)
;OR	A
;LD	A,B
;RET	P
;INC	A
;RET
;
;ZFD7C:	INC	C
;ZFD7D:	RRA
;JP	C,ZFD7C
;LD	A,C
;CP	10H
;JP	C,ZFDBD
;LD	D,20H
;CP	3FH
;LD	A,D
;INC	HL
;LD	A,(HL)
;JP	Z,ZFD96
;AND	40H
;JP	NZ,ZFD9C
;LD	A,C
;AND	1FH
;RET
;
;ZFD96:	AND	D
;LD	A,D
;RET	NZ
;LD	A,5FH
;RET
;
;ZFD9C:	LD	A,(HL)
;AND	D
;ADD	A,D
;LD	L,A
;LD	A,C
;AND	D
;JP	Z,ZFDAD
;LD	A,(FFIX)
;CPL
;AND	60H
;XOR	L
;ADD	A,C
;RET
;
;ZFDAD:	LD	B,A
;LD	A,C
;CP	1CH
;JP	C,ZFDB5
;LD	B,30H
;ZFDB5:	LD	A,L
;SUB	D
;RRA
;ADD	A,10H
;XOR	B
;ADD	A,C
;RET
;
;ZFDBD:	LD	HL,TFDC5
;LD	B,0
;ADD	HL,BC
;LD	A,(HL)
;RET
;
;
;TFDC5:	DB	0CH,1FH,1BH,0,1,2,3,4,9,0AH,0DH
;DB	7FH,8,19H,18H,1AH
;
;
;TABLE INKEY
;
INTABL: LD	HL,TSU
	LD	BC,00FFH
	LD	A,(PKC)
	RLA
	JP	C,K00
	LD	A,C
	DEC	A
	RET
;
K00:	RLA
	LD	(HL),C
	JP	C,K01
	LD	(HL),B      ;υσ (TSU)
K01:	INC	HL
	RLA
	LD	(HL),C
	JP	C,K1
	LD	(HL),B      ;σσ (TSH)
;
K1:	DEC	C
	LD	D,09H
K2:	LD	A,C
	LD	(PKA),A
	RLCA
	LD	C,A
;
K3:	LD	A,(PKB)
	CP	0FFH
	JP	Z,K4
	LD	E,A
;
;INKEY_TIME
;
	LD	H,5
	LD	A,(IKEYTM)
KYT:	DEC	A
	JP	NZ,KYT
	DEC	H
	JP	NZ,KYT
;
	LD	A,(PKB)
	CP	E
	JP	Z,K5
;
K4:	LD	A,B
	ADD	A,08H
	LD	B,A
	DEC	D
	JP	NZ,K2
;
;χωθ.εσμε ξετ ξαφ.λμαχ.
;
	OR	0FFH
	RET
;
K50:	INC	B
K5:	RRA
	JP	C,K50
;
;B= N KEY
;
	LD	A,B
	LD	(TBT),A
	PUSH	AF
	LD	HL,(TBRUS)
	EX	DE,HL
	LD	HL,(TBRUS)
	LD	A,(TBLAT)
	LD	C,A
	LD	B,0
	ADD	HL,BC
	POP	BC
	LD	A,(FFIX)
	AND	A
	JP	Z,K6
	EX	DE,HL
K6:	LD	A,(TSH)
	AND	A
	JP	NZ,K61
	EX	DE,HL
K61:	LD	C,B
	LD	B,0
	ADD	HL,BC
	LD	A,(TSU)
	AND	A
	LD	A,(HL)
	JP	NZ,STR2
	AND	1FH
	RET
;
;-----------------------
;
;
ENDIF
;
;
;==========================
; ππ.χωχοδα σινχομα ξα TV
; α => TV
;
TV:	PUSH	HL
	LD	HL,(TVAV)
	EX	(SP),HL
	RET
;
TV_A:	PUSH	BC
	LD	C,A
	DEFB	6
;
; C => TV
;
TV2:	PUSH	BC
TBC:	PUSH	DE
	PUSH	HL
	PUSH	AF

;IFE	MS
;CALL	INTRRP
;ENDIF

	LD	A,C 
	CP	1BH
	LD	A,0F0H
	JP	Z,UPR1
	LD	A,(AR2)
	AND	A
	JP	NZ,UST
ARINT:	LD	A,C
;
	CP	7	     ;BEEP ?
	JP	NZ,VT10
	CALL	BPX
	JP	EXX4
;
VT10:	CP	7FH
	JP	NZ,VT14
	LD	HL,INVERS
	LD	A,(HL)
	CPL
	LD	(HL),A
	JP	EXX4
;
VT14:	RLCA
	LD	A,C
	JP	NC,MMM1
	LD	HL,(ZNAK2)   ;αδςεσ ϊη: 80-FF
	EX	DE,HL
	LD	H,80H
	SUB	H
	JP	MMM2
;
MMM1:	LD	HL,(ZNAK1)   ;αδςεσ ϊη: 20-7F
	EX	DE,HL
	LD	H,20H
	SUB	H
	JP	C,OP1	     ;<= A<20H
;
MMM2:	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL	     ;*8
	EX	DE,HL
	ADD	HL,DE
	EX	DE,HL
	CALL	MASC1
	EX	DE,HL
	LD	A,16H
V22:	PUSH	AF  
	PUSH	HL
	LD	A,(INVERS)
	XOR	(HL)
	AND	3FH
	LD	L,A
	LD	A,(TB1)
	DEC	A
	LD	H,0H
V21:	ADD	HL,HL
	ADD	HL,HL
	INC	A
	JP	NZ,V21
	EX	DE,HL
	LD	A,B
	XOR	(HL)
	AND	(HL)
	OR	D
	LD	(HL),A
	INC	H
	LD	A,C
	XOR	(HL)
	AND	(HL)
	OR	E
	LD	(HL),A
	DEC	H
	INC	L
	EX	DE,HL
	POP	HL
	INC	HL
	POP	AF
	SUB	03H
	JP	P,V22
	LD	HL,OPER+1
	CP	0F8H
	JP	NZ,V22
OP1:	LD	HL,(TVAD)
	CALL	OPER
	ADD	HL,BC
	LD	A,H
	CP	19H
	JP	C,V3
	JP	NZ,V4
	INC	D
	LD	H,D
	JP	Z,V3
;
;	   SCROLL
;
	PUSH	HL
	LD	HL,0H
	ADD	HL,SP
	LD	(VSTACK),HL
	LD	A,(EKRED)
	LD	B,A
	LD	A,(EKRAN)
	LD	H,A
	LD	A,(SWIN)
	LD	L,A
	CALL	MULT10
	LD	C,A
RL0:	LD	A,C
	ADD	A,0AH
	LD	L,A
	LD	SP,HL
	LD	L,C
	LD	A,0F0H
RL1:	POP	DE
	LD	(HL),E
	INC	L
	LD	(HL),D
	INC	L
	POP	DE
	LD	(HL),E
	INC	L
	LD	(HL),D
	INC	L
	CP	L
	JP	NC,RL1
	LD	A,(INVERS)
RL2:	INC	SP
	LD	(HL),A
	INC	L
	JP	NZ,RL2
	INC	H
	DEC	B
	JP	NZ,RL0
	LD	HL,(VSTACK)
	LD	SP,HL
	POP	HL
V4:	LD	H,18H
V3:	LD	(TVAD),HL
EXX4:	POP	AF
STR2:	POP	HL
	POP	DE
	POP	BC
	RET
;
OPER:	LD	BC,100H
	LD	D,C
	INC	A
	CALL	Z,GTV
	JP	Z,V5
	CP	0EBH
	RET	Z
	DEC	D
	ADD	A,5H
	RET	Z
	INC	D
	LD	B,0FFH
	INC	A
	RET	Z
	LD	C,0FCH
	CP	0EFH
	RET	Z
	LD	BC,0H
	CP	0F0H
	JP	NZ,VDOP
	LD	A,L
	AND	0E0H
	ADD	A,20H
	LD	L,A
	RET
;
VDOP:	LD	C,04H
	INC	A
	RET	Z
V6:	ADD	A,0BH
	JP	Z,V7
	INC	A
	RET	NZ
V5:	LD	H,D
V7:	LD	L,D
	LD	B,D
	LD	C,D
	RET
;
UST1:	LD	A,C
	CP	59H
	JP	NZ,UST2
	LD	A,02H
	OR	B
UPR1:	LD	(AR2),A
	JP	EXX4
;
UST:	LD	B,A
	AND	03H
	JP	Z,UST1
	DEC	A
	JP	Z,MEST
	DEC	A
	JP	Z,STROK
UST2:	XOR	A
	LD	(AR2),A
	LD	A,C
	CP	4AH
	JP	Z,SNC
	CP	4BH
	JP	Z,SPC
	LD	HL,ARINT
	PUSH	HL
	LD	HL,ARINT
	PUSH	HL
	LD	C,18H
	CP	43H
	RET	Z
	INC	C
	CP	41H
	RET	Z
	INC	C
	CP	42H
	RET	Z
	LD	C,08H
	CP	44H
	RET	Z
	LD	C,0CH
	CP	48H
	RET	Z
	LD	C,1FH
	CP	45H
	RET	Z
	CP	C
	RET	Z
	POP	HL
	JP	EXX4
;
MEST:	LD	A,C
	SUB	20H
	RLCA
	RLCA
	AND	0FCH
	LD	(TVAD),A
	XOR	A
	JP	UPR1
;
STROK:	LD	A,C
	SUB	20H
	LD	(TVAD1),A
	LD	A,0F1H
	JP	UPR1
;
; ππ οώιστλι όλςαξα
;
GTV:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	AF
	LD	A,(SWIN)
	JP	SNSZ
;
SNC:	LD	A,(TVAD1)	 ;στες.ξιφ.λυςσ.
	INC	A
SNSZ:	CP	19H
	JP	NC,EXX4
	LD	L,A
	CALL	MULT10
	LD	C,A
	LD	A,(EKRAN)
	LD	H,A
	LD	A,(EKRED)
	LD	B,A
	DEC	H
SNC2:	INC	H
	LD	L,C
	LD	A,(INVERS)
SNC3:	LD	(HL),A
	INC	L
	JP	NZ,SNC3
	DEC	B
	JP	NZ,SNC2
	JP	EXX4
;
SPC:	LD	HL,(TVAD)	 ;στες.πςαχ.λυςσ.
	PUSH	HL
	LD	B,L
	LD	C,20H
SPC1:	CALL	TV2
	LD	A,04H
	ADD	A,B
	LD	B,A
	JP	NZ,SPC1
	POP	HL
	JP	V3
;
;
IF	Z80CPU
;
; ππ.BEEP δμρ "CARD2+Z80"
;
BEEP:	PUSH	BC
	LD	C,20H
BP1Z:   LD	A,(CBEEP)
	OUT	(0FFH),A
BP2Z:	DEC	A
	JP	NZ,BP2Z
	DEC	C
	JP	NZ,BP1Z
	POP	BC
	RET
;
ELSE
;
;
BEEP:	PUSH	BC
        LD 	C,20H
BP1:	LD	A,(CBEEP)
BP2:	EI
        DCR	A
	JP	NZ,BP2
	LD	A,(CBEEP)
BP3:	DI
	DCR	A
	JP	NZ,BP3
	DCR	C
	JP	NZ,BP1
	POP	BC
	RET
;
ENDIF
;
;
M4KP:	DS	0FE4AH-M4KP,0
;
;
; υπαλοχ.ϊη
;
NAZG: 	DB	0FFH,0C0H,84H,0,4,'J`*',1FH,0AH
	DB	1FH,'*',11H,0EH,'Q'
	DB	0EH,11H,18H,19H,2,4,8,13H,3,4
	DB	'*',0CH,15H,12H,0DH
	DB	'&',2,4,'@',2,4,'H',4,2,8,4
	DB	'B',4,8,0,4,15H,0EH,15H,4,0,0
	DB	'$',1FH,'$',0,'@,',4,8
	DB	'@',1FH,'@',80H,','
	DB	0,1,2,4,8,10H,0,0EH,11H,13H,15H
	DB	19H,11H,0EH,4,0CH,'d'
	DB	0EH,0EH,11H,1,6,8,10H,1FH,1FH,1,2
	DB	6,1,11H,0EH,2,6,0AH,12H,1FH,22H,1FH
	DB	10H,1EH,'!',11H,0EH,7,8,10H,1EH
	DB	'1',0EH,1FH,1,2,4,'H',0EH,'1'
	DB	0EH,'1',0EH,0EH,'1',0FH,1,2,1CH,0
	DB	', ,,',0,',',4,8,2,4,8,10H,8,4,2
	DB	' ',1FH,0,1FH,' '
	DB	8,4,2,1,2,4,8,0EH,11H,1,2
	DB	4,0,4,0EH,11H,13H,15H,17H,10H,0EH,4
	DB	0AH,'1',1FH,'1',1EH,'1',1EH,'1'
	DB	1EH,0EH,11H,'P',11H,0EH,1EH,89H,1EH
	DB	1FH,'0',1EH,'0',1FH,1FH,'0'
	DB	1EH,'P',0EH,11H,'0',13H,11H,0FH
	DB	'Q',1FH,'Q',0EH,84H,0EH,'a1'
	DB	0EH,11H,12H,14H,18H,14H,12H,11H,90H
	DB	11H,1FH,11H,1BH,'5Q1',19H,15H,13H
	DB	'1',0EH,91H,0EH,1EH,'1',1EH,'P'
	DB	0EH,'Q',15H,12H,0DH,1EH,'1'
	DB	1EH,14H,12H,11H,0EH,11H,10H,0EH,1
	DB	11H,0EH,1FH,0A4H,0B1H,0EH
	DB	'Q*$QU',0AH,'1',0AH,4,0AH,'11'
	DB	0AH,'d'
	DB	1FH,1,2,0EH,8,10H,1FH,0EH,88H,0EH,0
	DB	10H,8,4,2,1,0,0EH,82H,0EH,0EH,11H
	DB	80H,0A0H,1FH,12H,'5',1DH,'5'
	DB	12H,4,0AH,'1',1FH,'1',1FH,'0'
	DB	1EH,'1',1EH,92H,1FH,1,6,'j'
	DB	1FH,11H,1FH,'0',1EH,'0',1FH,4,1FH
	DB	'5',1FH,'$',1FH,11H,90H,'1'
	DB	0AH,4,0AH,'11',13H,15H,19H
	DB	'1',15H,11H,13H,15H,19H,'1'
	DB	11H,12H,14H,18H,14H,12H,11H,7,89H
	DB	19H,11H,1BH,'5QQ',1FH,'Q'
	DB	0EH,91H,0EH,1FH,0B1H,0FH,'1'
	DB	0FH,5,9,11H,1EH,'1',1EH,'P'
	DB	0EH,11H,'P',11H,0EH,1FH,0A4H
	DB	'Q',0AH,4,8,10H,11H,'5',0EH,'5'
	DB	11H,1EH,'1',1EH,'1',1EH,'P',1EH
	DB	'1',1EH,'Q',19H,'5'
	DB	19H,0EH,11H,1,6,1,11H,0EH,11H
	DB	95H,1FH,0EH,11H,1,7,1,11H,0EH
	DB	95H,1FH,1,'Q',1FH,'A'
;
	.DEPHASE
	END

9H,'5'
	DB	19H,0EH,11H,1,6,1,11H,0EH,11H
	DB	95H,1FH,0EH,11H,1,7,1,11H,0EH
	DB	95H,1FH,1,'Q